// src/react-app/utils/displayFields.ts

export const getDisplayFields = (resource: string) => {
  const fields: { [key: string]: string[] } = {
    films: [
      'title',
      'episode_id',
      'opening_crawl',
      'director',
      'producer',
      'release_date',
      'characters',
      'planets',
      'starships',
      'vehicles',
      'species',
    ],
    people: [
      'name',
      'height',
      'mass',
      'hair_color',
      'skin_color',
      'eye_color',
      'birth_year',
      'gender',
      'homeworld',
      'films',
      'species',
      'vehicles',
      'starships',
    ],
    planets: [
      'name',
      'rotation_period',
      'orbital_period',
      'diameter',
      'climate',
      'gravity',
      'terrain',
      'surface_water',
      'population',
      'residents',
      'films',
    ],
    species: [
      'name',
      'classification',
      'designation',
      'average_height',
      'skin_colors',
      'hair_colors',
      'eye_colors',
      'average_lifespan',
      'homeworld',
      'language',
      'people',
      'films',
    ],
    starships: [
      'name',
      'model',
      'manufacturer',
      'cost_in_credits',
      'length',
      'max_atmosphering_speed',
      'crew',
      'passengers',
      'cargo_capacity',
      'consumables',
      'hyperdrive_rating',
      'MGLT',
      'starship_class',
      'pilots',
      'films',
    ],
    vehicles: [
      'name',
      'model',
      'manufacturer',
      'cost_in_credits',
      'length',
      'max_atmosphering_speed',
      'crew',
      'passengers',
      'cargo_capacity',
      'consumables',
      'vehicle_class',
      'pilots',
      'films',
    ],
  };

  return fields[resource] || null;
};
